# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print("NumPy version:", np.__version__)

NumPy version: 1.26.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1
a1 = np.random.rand(2, 3, 5)
a1

array([[[0.12372039, 0.99359446, 0.13983272, 0.214189  , 0.02144413],
        [0.25316988, 0.05592118, 0.54616012, 0.07760178, 0.44323416],
        [0.10339915, 0.69751529, 0.24819607, 0.66993707, 0.84298265]],

       [[0.9426549 , 0.54220607, 0.07470951, 0.12434577, 0.72795664],
        [0.00209283, 0.8967361 , 0.31101991, 0.65955998, 0.02303164],
        [0.89749245, 0.61756548, 0.22071756, 0.46533529, 0.94291853]]])

In [8]:
# Method 2
a2 = np.random.randn(2, 3, 5)
a2

array([[[ 1.45337837, -0.61747123,  1.91021438, -0.68229135,
         -0.51971562],
        [-1.02076481,  0.10299314, -0.75793206, -0.93655611,
          0.42916557],
        [ 0.69402185, -2.38871866,  0.34124323,  0.18840411,
         -0.45173362]],

       [[-0.12837385,  0.16656318, -1.98937092, -0.08805506,
          0.98012164],
        [-0.78784174,  0.03452597,  0.35767433, -0.49635662,
         -1.72584001],
        [ 0.09277782,  1.36203928,  0.62371528, -0.4327459 ,
         -2.27548824]]])

In [9]:
# Method 3
a3 = np.random.random_sample((2, 3, 5))
a3

array([[[0.40545894, 0.70476985, 0.77879837, 0.13103726, 0.97865374],
        [0.78443444, 0.65630932, 0.29011262, 0.07212173, 0.57539317],
        [0.74578694, 0.05255202, 0.37743667, 0.65704361, 0.96858334]],

       [[0.31972564, 0.62374687, 0.50262516, 0.16984006, 0.65360119],
        [0.5456803 , 0.58911863, 0.94918227, 0.5811156 , 0.74867151],
        [0.28965223, 0.98993834, 0.86788355, 0.54817999, 0.85629128]]])

#### 4. Print *a*.


In [11]:
# your code here
print(a1)
print(a2)
print(a3)

[[[0.12372039 0.99359446 0.13983272 0.214189   0.02144413]
  [0.25316988 0.05592118 0.54616012 0.07760178 0.44323416]
  [0.10339915 0.69751529 0.24819607 0.66993707 0.84298265]]

 [[0.9426549  0.54220607 0.07470951 0.12434577 0.72795664]
  [0.00209283 0.8967361  0.31101991 0.65955998 0.02303164]
  [0.89749245 0.61756548 0.22071756 0.46533529 0.94291853]]]
[[[ 1.45337837 -0.61747123  1.91021438 -0.68229135 -0.51971562]
  [-1.02076481  0.10299314 -0.75793206 -0.93655611  0.42916557]
  [ 0.69402185 -2.38871866  0.34124323  0.18840411 -0.45173362]]

 [[-0.12837385  0.16656318 -1.98937092 -0.08805506  0.98012164]
  [-0.78784174  0.03452597  0.35767433 -0.49635662 -1.72584001]
  [ 0.09277782  1.36203928  0.62371528 -0.4327459  -2.27548824]]]
[[[0.40545894 0.70476985 0.77879837 0.13103726 0.97865374]
  [0.78443444 0.65630932 0.29011262 0.07212173 0.57539317]
  [0.74578694 0.05255202 0.37743667 0.65704361 0.96858334]]

 [[0.31972564 0.62374687 0.50262516 0.16984006 0.65360119]
  [0.5456803  0.

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [13]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [14]:
# your code here
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))
size_a = np.prod(a.shape)
size_b = np.prod(b.shape)
if size_a == size_b:
    print("Arrays a and b have the same size.")
else:
    print("Arrays a and b do not have the same size.")

Arrays a and b have the same size.


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here
No, we cannot directly add arrays a and b because they have different shapes. In NumPy, for element-wise addition (or any other element-wise operation), the arrays being operated on must have compatible shapes, meaning their dimensions must be either equal or one of them must be 1. This is known as broadcasting.



#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [17]:
# your code here
a.shape
b.shape
c = np.transpose(b, (1, 2, 0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [18]:
# your code/answer here
d = a + c
d.shape

(2, 3, 5)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [19]:
# your code/answer here
print("Array a:")
print(a)
print("\nArray d:")
print(d)

Array a:
[[[0.23016769 0.38653295 0.63428955 0.89862025 0.57625589]
  [0.78480823 0.9833774  0.89707126 0.36465205 0.28121634]
  [0.59726848 0.69367567 0.72663773 0.10155277 0.96108291]]

 [[0.14712196 0.72866382 0.02696693 0.1455818  0.77649681]
  [0.30544829 0.98936855 0.50217418 0.06913222 0.76779621]
  [0.85379588 0.06325386 0.09888694 0.38773498 0.42212816]]]

Array d:
[[[1.23016769 1.38653295 1.63428955 1.89862025 1.57625589]
  [1.78480823 1.9833774  1.89707126 1.36465205 1.28121634]
  [1.59726848 1.69367567 1.72663773 1.10155277 1.96108291]]

 [[1.14712196 1.72866382 1.02696693 1.1455818  1.77649681]
  [1.30544829 1.98936855 1.50217418 1.06913222 1.76779621]
  [1.85379588 1.06325386 1.09888694 1.38773498 1.42212816]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [20]:
# your code here
e = a * c
e

array([[[0.23016769, 0.38653295, 0.63428955, 0.89862025, 0.57625589],
        [0.78480823, 0.9833774 , 0.89707126, 0.36465205, 0.28121634],
        [0.59726848, 0.69367567, 0.72663773, 0.10155277, 0.96108291]],

       [[0.14712196, 0.72866382, 0.02696693, 0.1455818 , 0.77649681],
        [0.30544829, 0.98936855, 0.50217418, 0.06913222, 0.76779621],
        [0.85379588, 0.06325386, 0.09888694, 0.38773498, 0.42212816]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [21]:
# your code/answer here+
are_equal = np.array_equal(a, e)
are_equal

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [22]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print("Maximum value in array d:", d_max)
print("Minimum value in array d:", d_min)
print("Mean value of array d:", d_mean)

Maximum value in array d: 1.98936855299646
Minimum value in array d: 1.026966929281195
Mean value of array d: 1.5133919915204714


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [23]:
# your code here
f = np.empty_like(d)
f

array([[[0.23016769, 0.38653295, 0.63428955, 0.89862025, 0.57625589],
        [0.78480823, 0.9833774 , 0.89707126, 0.36465205, 0.28121634],
        [0.59726848, 0.69367567, 0.72663773, 0.10155277, 0.96108291]],

       [[0.14712196, 0.72866382, 0.02696693, 0.1455818 , 0.77649681],
        [0.30544829, 0.98936855, 0.50217418, 0.06913222, 0.76779621],
        [0.85379588, 0.06325386, 0.09888694, 0.38773498, 0.42212816]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [24]:
# your code here
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
                
f

array([[[ 25.,  25.,  75.,  75.,  75.],
        [ 75.,  75.,  75.,  25.,  25.],
        [ 75.,  75.,  75.,  25.,  75.]],

       [[ 25.,  75.,   0.,  25.,  75.],
        [ 25., 100.,  25.,  25.,  75.],
        [ 75.,  25.,  25.,  25.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [25]:
# your code 
print("Array d:")
print(d)
print("\nArray f:")
print(f)

Array d:
[[[1.23016769 1.38653295 1.63428955 1.89862025 1.57625589]
  [1.78480823 1.9833774  1.89707126 1.36465205 1.28121634]
  [1.59726848 1.69367567 1.72663773 1.10155277 1.96108291]]

 [[1.14712196 1.72866382 1.02696693 1.1455818  1.77649681]
  [1.30544829 1.98936855 1.50217418 1.06913222 1.76779621]
  [1.85379588 1.06325386 1.09888694 1.38773498 1.42212816]]]

Array f:
[[[ 25.  25.  75.  75.  75.]
  [ 75.  75.  75.  25.  25.]
  [ 75.  75.  75.  25.  75.]]

 [[ 25.  75.   0.  25.  75.]
  [ 25. 100.  25.  25.  75.]
  [ 75.  25.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here